# Server Port
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/cms
spring.datasource.username=root
spring.datasource.password=root

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
